### ISSUE TITLE
Support for other Executors

### ISSUE THREAD

**Issue by Dafuuh** [AlexR32/Parvus#59]
Since Krampus was discontinued, is it possible to add support for Incognito Executor? Solara is not an option because it doesn't have coregui.

That's the error code I'm getting. I hope it's an easy fix. Thank you for reading this.
![image](https://github.com/AlexR32/Parvus/assets/169771090/23aa5103-67f0-47b0-aef3-7c526d8b4f1b)

Regards,

Justin

**Comment by AlexR32** [comment]
Yes, it's possible to fix, just direct message owner of the executor and ask him for full UNC support (this might took them months to make and probably they will just ignore you)
I will not make concessions so that these executors work with my script.
