### ISSUE TITLE
Error when attempting to execute the script.

### ISSUE THREAD

**Issue by guhiclell** [AlexR32/Parvus#64]
When attempting to execute the script, it gives an error about utilites, I suspect my executor, Solara, and most other executors are unable to load the GUI.

Is it possible to change the GUI in a way that makes it compatible with other executors? 

I completely understand if its too difficult, straight up impossible or you just dont want to, but I figured I would ask as I used to use this script with KRNL before byfron and loved it! 

Regards,
[my shitty github name]

**Comment by Anbubu1** [comment]
Solara is unsupported. MacSploit would be the only working one as far as I know. Wave might work with it once it finally supports newcclosures with hookfunctions.
