### ISSUE TITLE
Almost all features not working

### ISSUE THREAD

**Issue by AbsurdIdealist** [AlexR32/Parvus#8]
Hi, 

I have tried multiple times using Parvus on BRM5. However, every time I try it, all most all of the features just don't work. I am using Script-Ware M and can you please fix it?

Sincere regards.

**Comment by Eziomeme** [comment]
BRM5 LOADS AT THE END OF ROUND OR BASICALLY DONT WORK FIX PLS

**Comment by Eziomeme** [comment]
hi i was playing Black Hawk Mission 5 or BRM5 and at Open Wolrd the script didnt work for me and at the 2v2 and 5v5 work at end of round. AR2 its hard make the script work. im using evon any problem or i need of krnl ?

**Comment by AlexR32** [comment]
This script only officially supports Synapse X, so I can't guarantee it will work on all executors.
As for Script-Ware M, it's broken and I won't fix my script for it anyway.

**Comment by Eziomeme** [comment]
in the evon its possible u fix or any Executor free ? bc 20 Dol at brazil is a little bit hard to pay at 1 executor
